# Fly.io config for AI Analysis Service
app = "elpyfi-ai"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "services/elpyfi-ai/Dockerfile"
  context = "services/elpyfi-ai"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.http_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    method = "get"
    path = "/health"